### PR TITLE
Plugin validation plus testing for x86_64 builds

### PR DESCRIPTION
**Pull request by falkTX**
This PR adds ttl syntax validation through lv2/sord_validate.
These tools need to be installed on the system, we can't use the buildroot ones. On Debian or Ubuntu, just install `lilv-utils`.

Additionally, we can also do runtime tests for x86_64 builds.
These will run through carla in a dummy audio engine (so no need for jack or anything like that) for 5 seconds with transport rolling.

Note both of these require running bootstrap again, but no need to delete old contents, just running it again to get the new files.

Here is some example usage, assuming plugins were built before.

1. For cross-compilation plugins:
```
./validate moddwarf abgate  
Checking abGate.lv2...
Found 0 errors among 106 files (checked 2103 restrictions)
Found 1 plugin(s)
```

2. For quick runtime check of x86_64 plugins:
```
./validate x86_64 artyfx
Checking artyfx.lv2...
Found 0 errors among 118 files (checked 3344 restrictions)
Found 3 plugin(s)
Verifying http://www.openavproductions.com/artyfx#filta... ok
Verifying http://www.openavproductions.com/artyfx#kuiza... ok
Verifying http://www.openavproductions.com/artyfx#roomy... ok
```

3. Validating and running x86_64 plugins through valgrind:
```
VALGRIND=1 ./validate x86_64 rkrlv2
Checking rkr.lv2...
Found 0 errors among 186 files (checked 21229 restrictions)
Found 5 plugin(s)
Valgrind check http://rakarrack.sourceforge.net/effects.html#StompBox_fuzz...
==1606199== Memcheck, a memory error detector
==1606199== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1606199== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==1606199== Command: /home/falktx/mod-workdir/x86_64/target/lib/carla/carla-bridge-native lv2  http://rakarrack.sourceforge.net/effects.html#StompBox_fuzz
==1606199== 
==1606199== Conditional jump or move depends on uninitialised value(s)
==1606199==    at 0x6DC9AA8: getFeatures(_RKRLV2*, LV2_Feature const* const*) (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x6DCAAF6: init_stomp_fuzzlv2(LV2_Descriptor const*, double, char const*, LV2_Feature const* const*) (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x4A0178: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x4A8604: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x40D471: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x406A3D: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x502F0B2: (below main) (libc-start.c:308)
==1606199== 
==1606199== Conditional jump or move depends on uninitialised value(s)
==1606199==    at 0x6E001F4: StompBox::init_tone() (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x6E007E9: StompBox::setpreset(int) (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x6DCAB2A: init_stomp_fuzzlv2(LV2_Descriptor const*, double, char const*, LV2_Feature const* const*) (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x4A0178: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x4A8604: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x40D471: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x406A3D: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x502F0B2: (below main) (libc-start.c:308)
==1606199== 
==1606199== Use of uninitialised value of size 8
==1606199==    at 0x6E0020C: StompBox::init_tone() (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x6E007E9: StompBox::setpreset(int) (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x6DCAB2A: init_stomp_fuzzlv2(LV2_Descriptor const*, double, char const*, LV2_Feature const* const*) (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x4A0178: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x4A8604: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x40D471: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x406A3D: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x502F0B2: (below main) (libc-start.c:308)
==1606199== 
==1606199== Conditional jump or move depends on uninitialised value(s)
==1606199==    at 0x6DCCBA8: AnalogFilter::setfreq(float) (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x6E0050A: StompBox::init_tone() (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x6E007E9: StompBox::setpreset(int) (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x6DCAB2A: init_stomp_fuzzlv2(LV2_Descriptor const*, double, char const*, LV2_Feature const* const*) (in /tmp/mpb-plugin-check/rkr.lv2/rkrlv2.so)
==1606199==    by 0x4A0178: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x4A8604: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x40D471: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x406A3D: ??? (in /Shared/mpb-workdir/x86_64/target/usr/lib/carla/carla-bridge-native)
==1606199==    by 0x502F0B2: (below main) (libc-start.c:308)
...
```

The last one is quite noisy, rkr seems to need some attention :)
(Though I would say that is kinda expected)

You might sometimes see a
```
Carla assertion failure: "msecs > 0" in file ../utils/CarlaUtils.hpp, line 310
```
When running with valgrind, I will see about fixing this soon. can be safely ignored.

### CODE REVIEW

**Comment by BramGiesen** [comment]
Just tested it, and it seems to work well so I think this can be merged. There is only one minor thing that I can think of; it might be good to update the README as well, to provide some documentation about these new features.

**Comment by falkTX** [comment]
Yes, including the publishing as well.

The validate requires some stuff pre-installed, and carla might still need some tweaks, so if we add to readme it should be marked as experimental for the time being.

Can you do this part?

**Comment by BramGiesen** [comment]
Sure, is it only the `lilv-utils` that needs to be installed locally for the validate feature?

**Comment by falkTX** [comment]
I just checked, we need `sord_validate` and `lv2ls`.
So that is `sordi` and `lilv-utils`, respectively.

**Comment by BramGiesen** [comment]
Okay, I have added it. Please, have a look if the info is correct and complete now. If so, this can be merged.

**Comment by falkTX** [comment]
Yes, all is good. We can merge now

**Pull request merged**
