### PR TITLE
Add stone-phaser package

### PR DESCRIPTION
**Pull request by jpcima**
Hi, this adds stone-phaser, an imitation of a classic analog phaser pedal.
The package includes a modgui.

### CODE REVIEW

**Comment by falkTX** [comment]
Thanks!

But the host package tickery is a bit ugly, there are ways to run the cross-compiled binaries on a regular pc. this clears a lot the mk file.

**Comment by jpcima** [comment]
I assume with help of qemu?
I didn't find an example of using it, and dragonfly-reverb didn't build in my docker.

But now I think of it, I don't have qemu's binfmt on the host, it may explain why I have the "exec format error".

**Comment by falkTX** [comment]
You only need to enable the new archs, add the ports and install a few packages.
Take a look at https://github.com/moddevices/mod-plugin-builder/blob/master/docker/Dockerfile for an example

Though that is for Ubuntu based systems. On debian the ports separate repos are not needed.
I do not know how to enable this in other distros, might not even be possible as it requires a multi-arch repo setup

**Comment by jpcima** [comment]
I was using the docker.
As I discovered, binfmt and static qemu must be installed on the host, then it works.

**Pull request merged**
