### PR TITLE
Fixing pkgconf URLs

### PR DESCRIPTION
**Pull request by rominator1983**

### CODE REVIEW

**Comment by rominator1983** [comment]
@falkTX please check this once for yourself. I did a build with PopOs! that seemed to work despite my changes here.

Anyhow the old pkgconf URLs are not reachable anymore so I updated those. Someone must have deleted all the releases in favor of the tags. Github seems to provide a .tar.gz for tags out of the box.

I also do not know how things worked without the autoreconf call. Most of those things are beyond my C/C++/make skills. I hope you know, what to make of this.

**Comment by falkTX** [comment]
some of the changes here are really superfulous, glibc-source as dependency makes no sense.

only way I see around this is to put some automated testing for a bunch of distros at once.

**Comment by rominator1983** [comment]
i see. it seemed that this would have been necessary but I do get a feeling of why it really isn't.

Anyways the call to autoreconf also does not work since the directory is missing first.
Do you maybe know why my ./configure would be missing for host-pkgconf?

**Comment by rominator1983** [comment]
so a bunch of libraries (libc ...) are built before the plugins can be built on a system. Might it be that the separation of the libraries is not that perfect?

I had some errors that definitively went away after for example installing libpulse-dev

**Comment by rominator1983** [comment]
I'll reduce the PR to the fix of the URLs. I think that might really be needed.

**Comment by rominator1983** [comment]
that's done. Ok for you @falkTX

**Comment by rominator1983** [comment]
Ok. I have confirmed it with PopOs! too.
The configure-File needs to be created with an autoreconf call. But the call can't be made before the host-pkgconf-directory is present.

I do not really know why that is and if the old (non existent) .tar.bz2 of pkgconf had a configure file in it.
@falkTX  Do you know where there could be a hook to call autoreconf for host-pkgconf?

**Comment by falkTX** [comment]
> I do not really know why that is and if the old (non existent) .tar.bz2 of pkgconf had a configure file in it.
> @falkTX Do you know where there could be a hook to call autoreconf for host-pkgconf?

we need to use a proper release tarball and not one generated from github, as that is a 1:1 copy of the git repo so that is why it misses those files.
actual release tarballs have some steps done by upstream to generate these files in an automatic way.

**Comment by falkTX** [comment]
from pkgconf readme they state we should use https://distfiles.ariadne.space/pkgconf as tarball download URL.
that includes the file we need, and sum matches:

```sh
$ sha256sum pkgconf-0.9.12.tar.bz2
7ec8b516e655e247f4ba976837cee808134785819ab8f538f652fe919cc6c09f  pkgconf-0.9.12.tar.bz2
```

**Comment by rominator1983** [comment]
Then I will use that and adapt my PR

**Comment by rominator1983** [comment]
done @falkTX

**Comment by rominator1983** [comment]
the last commit added a patch for locale.h in order to fix https://github.com/moddevices/mod-plugin-builder/issues/175

**Comment by falkTX** [comment]
Thanks, I still want to add some CI jobs to test all these different distro versions...
Specially important for newer ones that have not yet been tested

**Comment by falkTX** [comment]
CI stuff is in place, and we can confirm the build issue indeed.

Please rebase/update this PR against latest master, thanks!

**Comment by rominator1983** [comment]
sorry for the delay. I did sync

**Comment by falkTX** [comment]
thanks, now we wait to see if all is good.

**Comment by rominator1983** [comment]
oh. so you do mainly build on debian and ubuntu too? good to know.
I will probably switch to Ubuntu studio since pipewire does not produce acceptable latencies in my setup as of some recent update and jack seems only to be supported reasonably well in Ubuntu Studio :-(

**Comment by falkTX** [comment]
> oh. so you do mainly build on debian and ubuntu too? good to know.

personally yes, so this is easy to setup in CI. but we want to have at least archlinux in there too, so we test a rolling release with the freshest stuff.

**Comment by falkTX** [comment]
Your 2nd file is malformed and fails to apply.

```
2023-10-29T21:44:08.3398637Z Applying 002_bits_types_locale_t.patch using patch: 
2023-10-29T21:44:08.3417263Z can't find file to patch at input line 3
2023-10-29T21:44:08.3417943Z Perhaps you used the wrong -p or --strip option?
2023-10-29T21:44:08.3418508Z The text leading up to this was:
2023-10-29T21:44:08.3418981Z --------------------------
2023-10-29T21:44:08.3419612Z |--- a/glibc/locale/locale.h	2023-10-23 23:21:09.629352607 +0200
2023-10-29T21:44:08.3421661Z |+++ b/glibc/locale/locale.h	2023-10-23 23:20:54.853093115 +0200
2023-10-29T21:44:08.3422306Z --------------------------
2023-10-29T21:44:08.3422707Z No file to patch.  Skipping patch.
2023-10-29T21:44:08.3423169Z 1 out of 1 hunk ignored
2023-10-29T21:44:08.3423681Z Patch failed!  Please fix 002_bits_types_locale_t.patch!
2023-10-29T21:44:08.3425582Z make: *** [package/pkg-generic.mk:163: /github/home/mod-workdir/modduox/build/host-localedef-2.14.1-r17443-ptx1/.stamp_patched] Error 1
```

**Comment by rominator1983** [comment]
i see. must have been some change in the meantime. i will check on my machine

**Comment by rominator1983** [comment]
but its definitely a 23.10 thing considering the build output

**Comment by rominator1983** [comment]
where did you find this in the logs?

**Comment by rominator1983** [comment]
ah. got it. one failed the others were cancelled

**Comment by rominator1983** [comment]
I did a fix for this on my Ubuntu 23.10. Probably also working on Ubuntu Studio 23.10 where this is still running.

I do not know if this will work on any other machines since builds were green before this change and this was my fix to the malformed patch file: https://github.com/moddevices/mod-plugin-builder/pull/174/commits/c2014c368e2efb7e1cc657014e01a6e2de916603

Looks like the folder is eglibc on 23.10 and glibc on other machines?

**Comment by falkTX** [comment]
the packages should be the same for all distros.

anyhow, I should have a deeper look at this. lets see what the next build says.

**Comment by rominator1983** [comment]
well that seemed to do the trick

**Comment by falkTX** [comment]
cool yes, finally :)

thank you, merging now then

**Pull request merged**
