### PR TITLE
Update ALO

### PR DESCRIPTION
**Pull request by devcurmudgeon**
- ignore small fluctuations in BPM
- add per-beat-loops

### CODE REVIEW

**Comment by devcurmudgeon** [comment]
@BramGiesen any news on this please?

**Comment by BramGiesen** [comment]
@devcurmudgeon sorry for the slow response. It has been an very busy week for me, but I will have time to have a look at the PR tomorrow.

**Comment by devcurmudgeon** [comment]
Thanks @BramGiesen - incidentally would it be possible to move ALO to the main store, rather than Beta?

**Comment by BramGiesen** [comment]
@devcurmudgeon I've checked the PR. It looks good, so I will merge it and update the plugin is the store. Regarding moving it to the main store, it might be possible to do so. However, we will be reorganizing some things in our store very soon, most likely in the next couple of weeks, so it might be best to have a look at this once that is done.

**Pull request merged**
