### PR TITLE
Added MrFreeze plugin

### PR DESCRIPTION
**Pull request by romi1502**
Added the MrFreeze plugin.
The plugin seems to build smoothly and run on the Mod.

### CODE REVIEW

**Comment by falkTX** [comment]
before accepting, I have a few questions..
why do you download eigen in the configure script?
eigen is included in the mod-plugin-builder builds, please use that.

how exactly did you generate mrfreeze.wisdom.duo?
the exact command needs to be specified somewhere.

I see a very big issue in the plugin code.
you use std::queue and std::vector during processing. this allocates memory, which is not realtime safe.
using these classes would mean the plugin will consume a lot of dsp time (even if cpu is not high).
Seems to me you get a lot of audio xruns this code, right?

**Comment by romi1502** [comment]
Hi @falkTX 
I removed the call to configure.sh in the *.mk file, added eigen in the dependencies and changed accordingly our Makefile. Now it builds using directly the eigen version of the mod-plugin-builder.

The mrfreeze.wisdom.duo was generated with the following command:
`fftwf-wisdom -n -x -o mrfreeze.wisdom.duo rof1024 rob1024 rof2048 rob2048`
ran directly on the mod. Where should I specify it ?

Concerning the xruns: I don't experience xruns when the plugin is loaded alone in the Mod, this is why I considered the plugin mature enough to be released as unstable.
However, when several plugins are loaded and the cpu load is a bit high (while still quite under 100%), I do experience some xruns that may be related to the use of not realtime safe objects. The guy who did most of the C++ stuff (bx5a on github) would probably be more helpful on this issue, but he is currently in holiday.

**Comment by falkTX** [comment]
Alright, looks good enough for now.
Since it's not targeted for stable, it can go to the store as it is.

**Comment by falkTX** [comment]
actually after a 2nd look, I notice that your bundle name is mod-mrfreeze.lv2.
please use mrfreeze.lv2 instead, taking out the mod prefix.
thanks

**Comment by romi1502** [comment]
Ok, I just did it. Do I do a new pull request ?

**Pull request merged**
